### ISSUE TITLE
GPT variable in lyrics text

### ISSUE THREAD

**Issue by mirh** [fr31/spotifylyrics#1]
https://open.spotify.com/track/2T13fabFHPytple2z3Ekhj

I hope is reproducible.

**Comment by fr31** [comment]
I'm not sure what a "GPT variable" is tbh. But I'm just getting "Error: Could not find lyrics." for that song.

**Comment by mirh** [comment]
Google Publishing Tools, this is what I see. 

     googletag.cmd.push(function() { googletag.display("div-gpt-ad-q_g2soVEtQgAJMBaolHMFg"); })

And aside of this single line, the rest of the lyrics is fine then.

**Comment by fr31** [comment]
This is probably just a problem with how I pull the lyrics text out of the fetched webpage and is an easy fix, but unfortunately it's not even finding lyrics for that song for me so I don't even know which site it's scraping that from.

If you're running from source, or know how to run from source, and want to help me fix this problem. You can edit this section of backend.py:

> lyrics = lyrics_wikia(artist, song)
    if lyrics == error:
        lyrics = lyrics_musixmatch(artist, song)
    if lyrics == error:
        lyrics = lyrics_songmeanings(artist, song)
    if lyrics == error:
        lyrics = lyrics_songlyrics(artist, song)
    if lyrics == error:
        lyrics = lyrics_genius(artist, song)

to be just one of the "lyrics = lyrics_website(artist, song)" lines (and go down the list if it can't find them), to find out where you're pulling the lyrics from that has that. Then I can filter it out of the text before it's displayed.

But otherwise, I can't reproduce it, unfortunately.

**Comment by mirh** [comment]
I think it's even easier man. 
[Wikia](http://lyrics.wikia.com/wiki/Special:Search?search=%22no+heroes%22+culture&fulltext=Search&ns0=1#), [songmeanings](http://songmeanings.com/query/?query=no%20heroes&type=songtitles) and [songlyrics ](http://www.songlyrics.com/index.php?section=search&searchW=no+heroes&submit=Search&searchIn3=song) haven't it. 
We are left with [musixmatch](https://www.musixmatch.com/lyrics/Firebeatz-KSHMR-feat-Luciana/No-Heroes-Original-Mix) and [genius](http://genius.com/Firebeatz-no-heroes-lyrics) then, and only the latter has the grammar I see in your program.

**Comment by fr31** [comment]
I think I fixed it. Could you try the latest release and confirm?

**Comment by mirh** [comment]
Yep ^^

**Comment by mirh** [comment]
For the records... 
I just updated to 1.0.32.96... and title bar became "Firebeatz - No Heroes (feat. Luciana) - Original Mix" from the usual "Firebeatz - No Heroes - Original Mix". 
And indeed I had no lyrics. 

After some playing random some other track.. title is now back normal :|

**Comment by mirh** [comment]
Ok, it's totally fucked up. 
It seems that with this track, and only this track, if Spotify is opened playing it.. name changes. 
@fr31 tagging because wtf.

**Comment by fr31** [comment]
It changes in the middle of playing it?

Mine says "Firebeatz - No Heroes (feat. Luciana) - Original Mix" and doesn't change.

I fixed it so it fetches the lyrics properly with that title btw. Gonna do the release/make the binaries tomorrow though.

**Comment by mirh** [comment]
> It changes in the middle of playing it?

It changes whenever I switch song, or press "backward" or "forward" buttons.

**Comment by fr31** [comment]
Does it cause any issues?

**Comment by mirh** [comment]
Well, the only issue was the one you saw: no matching lyrics. 

And I don't think it's something specifically about [feat.]. 
It's more like on launch, Spotify used "artist - album" format, instead of the normal "artist - song"
