### ISSUE TITLE
Lyrics are sometimes ahead

### ISSUE THREAD

**Issue by NoricoG** [fr31/spotifylyrics#12]
With synced lyrics, the current line is at the top and previous lines are not visible. With some songs the lyrics are a bit ahead, so the real current line of the song is not visible anymore. Also some songs have fast lyrics, so my brain needs some more time to process them. 

This could be solved by showing the previous line(s) as well, instead of putting the bold line at the top. Instead of a number of lines, this can also be done with a number of seconds to keep at the top above the bold line.
It could also be solved by letting the user add a delay or pick the current line of the song. This is also useful when the playing position in a song is changed by the user, but it might be complicated and could make the wrong line bold for this issue.

**Comment by fr31** [comment]
I will see what I can do.

**Comment by fr31** [comment]
The latest version will leave 2 lines of text above the bold line. Hope this solves this issue.

https://github.com/fr31/spotifylyrics/releases/

I'll look in to letting the user pick what line the song is currently on in the future. No guarantees though, as I'm not sure how difficult that will be.

**Comment by NoricoG** [comment]
Thanks, this solves it for me
