### ISSUE TITLE
Minilyrics are sometimes wrong

### ISSUE THREAD

**Issue by NoricoG** [fr31/spotifylyrics#13]
When a song is not available on minilyrics.com you can get the wrong lyrics, from a song with the same title but a different artist. To solve this I added
```python
if artist.lower() not in lyrics.lower():
            lyrics = error
```
After this I got different issues where the lyrics from other websites aren't visible, while the url does lead to a song (though this can be from a different songs as well). This is probably harder to fix.

Examples are:
- Glass Animals - Life Itself
- Lewis Del Mar - Painting (Masterpiece)
- The Shelters - Rebel Heart

**Comment by fr31** [comment]
Close! If you change your code to:

```python
if artist.lower() not in lyrics.lower():
    lyrics = error
    timed = False
```

It works just fine. But I found some songs where the artist had spaces in their name on spotify but the lyrics didn't for some reason (or visa versa). So I fixed it like this:

```python
if artist.lower().replace(" ", "") not in lyrics.lower().replace(" ", ""):
    lyrics = error
    timed = False
```

Seems to be working. I'll release an update it the morning probably.

**Comment by fr31** [comment]
Released a version with the fix.
