### ISSUE TITLE
Exception in getwindowtitle

### ISSUE THREAD

**Issue by archagy** [fr31/spotifylyrics#16]
Changing worksplace window  throw an exception in backend.py at line 160.

Adding a try catch for raise better log message.

```
     try:
            windows = subprocess.check_output(["/bin/bash", "-c", command]).decode("utf-8")
                       except subprocess.CalledProcessError as e:
             raise RuntimeError("command '{}' return with error (code {}): {}".format(e.cmd, e.returncode, e.output)) 
```

Throw the next exception: 

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "SpotifyLyrics.py", line 294, in lyrics_thread
    if songname != backend.getwindowtitle():
  File "/home/alex/dev/contributions/spotifylyrics/backend.py", line 162, in getwindowtitle
    raise RuntimeError("command '{}' return with error (code {}): {}".format(e.cmd, e.returncode, e.output))
RuntimeError: command '['/bin/bash', '-c', 'xwininfo -tree -root']' return with error (code 1): b'\nxwininfo: Window id: 0x225 (the root window) (has no name)\n\n  Root window id: 0x225 (the root window) (has no name)\n  Parent window id: 0x0 (none)\n     111 children:\n     0x4800022 (has no name): ()  1x1+-1+-1  +-1+-1\n     0x4800004 "Notification": ("mate-notification-daemon" "Mate-notification-daemon")  400x96+954+6  +954+6\n        1 child:\n        0x4800005 (has no name): () \n'

```

Using a virtual machine with linux mint 17 mate.

**Comment by fr31** [comment]
I can't seem to reproduce this on my ubuntu virtual machine. I've changed the workspace of both spotify and spotify lyrics by right clicking on the menu bar and clicking "switch to workspace x" and it still runs fine.

Could you describe the exact steps you're taking to make this happen?

**Comment by archagy** [comment]
Sure...

Run 
Workspace 3
![screenshot at 2016-08-04 11-54-20](https://cloud.githubusercontent.com/assets/4847289/17410675/57a7f516-5a3a-11e6-81c2-c6532d3a6683.png)

Spotify and another programs in other workspaces.

Changing constantly with ctr+shift and arrows....Throw exception.
![screenshot at 2016-08-04 11-59-22](https://cloud.githubusercontent.com/assets/4847289/17410798/e88ace50-5a3a-11e6-84e8-dc2721e2e4b4.png)

Also taking screenshot and cancel it throw another exception.

![screenshot at 2016-08-04 11-56-40](https://cloud.githubusercontent.com/assets/4847289/17410819/03f76266-5a3b-11e6-9401-3671cc4fe97c.png)


I dont know if it is because for my desktop enviroment MATE.


Regards~

**Comment by archagy** [comment]
Extra info:

When i run directly the command "xwininfo -tree -root | xclip "  return this:

http://pastebin.com/xA1xpyek

**Comment by archagy** [comment]
Well i can "Fix it" handle with the exception

```
while True:            
            try:
                windows = subprocess.check_output(["/bin/bash", "-c", command]).decode("utf-8")
                break
            except subprocess.CalledProcessError as e:
                print("command '{}' return with error (code {}): {}".format(e.cmd, e.returncode, e.output))
                continue
 
```       

With this code print the exception but the program still works.

I dont know if this it's the best way to fix the problem. 

Please let me know.

**Comment by fr31** [comment]
I think I fixed it in the latest master branch. Not the most elegant solution. I decided to switch to dbus to get the song name and artist instead of the window title only to realize there's no way to know if it's paused with dbus (that I could find), so right now it's a hybrid of the old way and the new. Your way may be better.

But, I think it should fix this issue though. Let me know.

**Comment by archagy** [comment]
Fixed!!
