### ISSUE TITLE
Ideas to get play time

### ISSUE THREAD

**Issue by mirh** [fr31/spotifylyrics#2]
So.. Normal API just [sucks](https://jonaslundqvist.net/2015/05/06/do-not-use-libspotify/). And everything possibly working has been [discontinued](https://community.spotify.com/t5/Help-Web-Player/Using-API-to-get-the-current-player-time/td-p/667332). 
And given this is a python project, I don't expect anybody to do any special in-memory hooking and searching. 
Though.. I noticed that at least in version 1.31, when you are playing tracks the Windows "title bar" name changes (from just "Spotify" to "*played song*"). 
If you knew how long said song is, couldn't you deduce the actual play time (assuming user hasn't touched it)?

EDIT: doing this on [linux](stackoverflow.com/questions/33883360/get-spotify-currently-playing-track/#33923095) should be [doable](https://github.com/spotify/web-api/issues/12#issuecomment-216105653).
Or [downgraded](stackoverflow.com/questions/29821881/fetch-the-current-track-info-from-spotify-app-after-march-2015-update/#29829117) windows app.

**Comment by fr31** [comment]
Are you suggesting that I display the song time/position in the application or?

**Comment by mirh** [comment]
The point, was more about having text in sync. 
That would bring your program to the same level of the bloody gone musixmatch implementation.

**Comment by fr31** [comment]
Ah, I understand now. I'll certainly try to get something working in my spare time but no guarantees as that may be above my current skill set. (also gotta figure out where to get timed lyrics from)

**Comment by mirh** [comment]
I feel almost embarrassed to give for granted that. 
Indeed, [musixmatch api](http://genius.com/developers) is quite nazi. 
Thankfully, genius seems [lovelier](http://genius.com/developers).

**Comment by AochiToxx** [comment]
This maybe too late of input. But I wouldn't mind setting up a rest server so we can allow users to make their own lyric timings. I know little of python. but I'm sure i can come up with the code to make it work if someone comes up with the visual interface.

**Comment by fr31** [comment]
I added support for lrc timed lyrics files in the latest test branch. Local files only atm because no sites provide lrc files. If you want to create a site that hosts lrc files @AochiToxx I'll make it fetch from there.

CPU usage pretty high for timed lyrics. Scrolling is a bit wonky. I recommend setting the text size so it doesn't have to scroll. 

I'm not too confident of the code I wrote, I'm sure it could be better if anyone else knows python wants to take a look and improve.

I used http://www.lrcgenerator.com/ to create the lyrics files for testing.

**Comment by mirh** [comment]
http://stackoverflow.com/questions/29062319/how-to-get-spotify-current-playing-song-in-python-windows#29191463

**Comment by fr31** [comment]
I'm not sure there's a need for that. It seems to only provide information I can already get via the window title.

**Comment by mirh** [comment]
.. Uh, I'm dumb. 
I dreamed a "track time" information to be somewhere. Sorry.

**Comment by fr31** [comment]
Haha, no worries.

**Comment by fr31** [comment]
Thanks to this project: https://github.com/rikels/LyricsSearch I had a place to get synced lyrics from.

Released a version with synced lyrics support: https://github.com/fr31/spotifylyrics/releases

Just gotta figure out a way to fix scrolling now.
