### ISSUE TITLE
[Installing] : Error loading Python DLL

### ISSUE THREAD

**Issue by puli83** [fr31/spotifylyrics#22]
Hi,

I have windows 7 64-bit, and python is properly installed in my computer (2.7 version). Anywaqy, I'm not able to execute the .exe. theses are my codes errors: 

1) api-ms-win-crt-runtime-l1-1-0.dll is not present in computer

and then this one is open in a new window

2) Error loading Python DLL: C:\users\...\AppData\Local\Temp\_MEI62842\python35.dll (error code 126)

How can I fix this issue?

**Comment by archagy** [comment]
Do you has fixed the error ?

**Comment by puli83** [comment]
Yes, thank you.

I've not seen the read me file.

You did a good job. Thank you

Davide Pulizzotto
