### ISSUE TITLE
Wrong lyric fetched but correct lyric at url by click the song title

### ISSUE THREAD

**Issue by KodaPOwER** [fr31/spotifylyrics#24]
Hello,
first of all congratz, the 1.11 version is great!

Sometimes happen that the lyrics fetched is wrong but if i click on the song title it open up the right url with the correct lyrics. Here a screenshoot to explain the mismatch.

![image](https://cloud.githubusercontent.com/assets/9638822/18082041/561b9b40-6e9d-11e6-8ce6-e4daa25aa024.png)

Have a nice day!

**Comment by fr31** [comment]
Seems to be a weird issue musixmatch scraper, not sure what's causing it but for now I'll re-order the scraping priority so this issue is minimized.

**Comment by KodaPOwER** [comment]
just tried the new version. it works!

If i have some spare time i'll try to learn a little of phyton so i can contribute at the project.
Coming from 10-years experience on c# and java so it don't seems to much difficult to learn!

Thanks for the workaround.
