### ISSUE TITLE
Book excerpt instead of lyric

### ISSUE THREAD

**Issue by Shanamaj** [fr31/spotifylyrics#27]
The song Adda - Iti Arat Ca Pot comically gives "lyrics" from site http://genius.com/Robert-c-tucker-the-marx-engels-reader-chapter-2-annotatedinstead of e.g. http://www.versuri.ro/versuri/gfjkel_adda-iti-arat-ca-pot.html

**Comment by fr31** [comment]
Sorry it took so long, but this issue should be fixed in the newest version.

**Comment by Shanamaj** [comment]
Works now, thanks! 👍
