### ISSUE TITLE
Issues grabbing songs from Musicxmatch and Genius.

### ISSUE THREAD

**Issue by Zvartefoss** [fr31/spotifylyrics#30]
Hey!

It seems your program is having issues finding lyrics for certain songs eventhough they are available on Musicxmatch and Genius, which, by looking a bit at your code seems to be two of the sites it searches.

![songlyrics](https://cloud.githubusercontent.com/assets/22743579/19234653/33781a80-8eed-11e6-8a21-ed2ad075d425.png)

**Comment by fr31** [comment]
This issue should be fixed in the latest version.
