### ISSUE TITLE
Synced Lyrics?

### ISSUE THREAD

**Issue by DanTm99** [fr31/spotifylyrics#32]
I don't know what turning on Synced Lyrics does, but whatever it's supposed to do doesn't look like it's working because when I do enable it, nothing seems to change

**Comment by fr31** [comment]
http://i.imgur.com/XSxvSMZ.gif

This is what it's supposed to do and appears to be working for me. It should highlight the currently playing lyric. (with some exceptions, it will de sync if you manually seek through the song)

If it can't find the synced lyrics of a song it will fall back to just displaying the regular lyrics though. Generally only happens with obscure songs.

**Comment by DanTm99** [comment]
Thanks for clearing that up. The problem seems to be that spotify doesn't have synced lyrics for a chunk of the songs in my library.
