### ISSUE TITLE
Chromecast Version

### ISSUE THREAD

**Issue by KeizerDev** [fr31/spotifylyrics#33]
Hi!

I really want to create a fork of this project just for a Chromecast support with the free version of spotify, but I can't do this alone. Are there any folks who want to join me starting this project?

For the Chromecast thing I want to use https://github.com/balloob/pychromecast

@fr31 what are your thoughts about it?

**Comment by fr31** [comment]
I don't have a chromecast and don't really know anything about them so I doubt I can be much help, but I'll help if I can.

**Comment by Ich5003** [comment]
That sounds like an awesome idea.
If i have the time for it I may write a program for that :)
