### ISSUE TITLE
javascript code instead of lyrics for https://open.spotify.com/track/51YEsxj20DD3BkAbEoSUjo

### ISSUE THREAD

**Issue by DaFlo1981** [fr31/spotifylyrics#36]
"var CURRENT_USER = null;
  var CANONICAL_DOMAIN = "genius.com";
  var CANONICAL_DOMAIN_PARTS_LENGTH = 2;
  var CURRENT_CHANNEL = "rock";
  var CURRENT_TAG = {"tag":{"always_allow_personal_annotation":null,"beefy":true,"created_at":"2013-12-11T08:56:58Z","deleted_at":null,"description":"Welcome to Rock Genius, where people just like you break down lyrics by your favorite rockers past and present.  Wondering about whether [all that glitters is gold?](http://genius.com/293677)  Wanna know if Jimi actually [kissed the sky?](http://genius.com/624357)  Need to keep up on [Against Me!'s historical references?](http://genius.com/2709135)  Curious about [why The Shins got back together with Zach Braff?](http://genius.com/3336641)  We've got it all!\r\n\r\nWhile you're here, follow us on [Twitter](https://twitter.com/rockgenius) and [Facebook](https://www.facebook.com/therockgenius)","designation":"featured_music","google_analytics_table_id":"ga:87826506","id":567,"image_url":"https://images.rapgenius.com/db11f012cb5d0a3066272732495b6ad3.480x360x12.gif","implied_channel_id":2,"languages_store":{},"logical_name":"rock","name":"Rock Genius","slug":"rock","taggings_count":148298,"twitter_name":"rockgenius","updated_at":"2015-07-30T21:10:50Z"}};
  var TRACKING_DATA = {"Song ID":2831858,"Title":"Electromod","Primary Artist":"Cachorro Grande","Primary Artist ID":361288,"Primary Album":"Electromod","Primary Album ID":162131,"Primary Tag":"rock","Primary Tag ID":567,"Has Relevant Videos?":false,"Music?":true,"Annotatable Type":"Song","Annotatable ID":2831858,"featured_video":false,"cohort_ids":[],"has_verified_callout":false,"has_featured_annotation":false,"created_at":"2016-08-03T18:31:37Z","created_month":"2016-08-01","created_year":2016,"song_tier":"E","Has Recirculated Articles":false};
  var VALID_SUBDOMAINS = ["x","news","rap","law","history","tech","rock","country","r-b","lit","pop","screen","meta","sports"];
  var EMBEDLY_KEY = "fc778e44915911e088ae4040f9f86dcd";
  var MOBILE_DEVICE = false;
  var APP_CONFIG = {"env":"production","api_root_url":"/api","facebook_app_id":"265539304824","facebook_opengraph_api_version":"2.5","pusher_app_key":"6d893fcc6a0c695853ac","embedly_key":"fc778e44915911e088ae4040f9f86dcd","app_store_url":"https://itunes.apple.com/us/app/genius-by-rap-genius-search/id709482991?ls=1&mt=8","play_store_url":"https://play.google.com/store/apps/details?id=com.genius.android","soundcloud_client_id":"632c544d1c382f82526f369877aab5c0","annotator_context_length":32,"comment_reasons":[{"_type":"comment_reason","context_url":"http://genius.com/8846441/Genius-how-genius-works/More-on-annotations","display_character":"R","handle":"Restates the line","id":1,"name":"restates-the-line","raw_name":"restates the line","requires_body":false,"slug":"restates_the_line"},{"_type":"comment_reason","context_url":"http://genius.com/8846441/Genius-how-genius-works/More-on-annotations","display_character":"S","handle":"It’s a stretch","id":2,"name":"its-a-stretch","raw_name":"it’s a stretch","requires_body":false,"slug":"its_a_stretch"},{"_type":"comment_reason","context_url":"http://genius.com/8846441/Genius-how-genius-works/More-on-annotations","display_character":"M","handle":"Missing something","id":3,"name":"missing-something","raw_name":"missing something","requires_body":false,"slug":"missing_something"},{"_type":"comment_reason","context_url":"http://genius.com/8846441/Genius-how-genius-works/More-on-annotations","display_character":"…","handle":"Other","id":4,"name":"other","raw_name":"other","requires_body":true,"slug":"other"}],"filepicker_api_key":"Ar03MDs73TQm241ZgLwfjz","filepicker_policy":"eyJleHBpcnkiOiIyMzIyMjM4OTI3IiwiY2FsbCI6WyJwaWNrIiwicGlja0FuZFN0b3JlIiwicmVhZCIsInN0b3JlIiwic3RhdCJdfQ==","filepicker_signature":"d155a1c0e33688b9bf17de68465df1ec0bfd18d7c5e95c944468f1ad5e9fc656","filepicker_s3_image_bucket":"filepicker-images-rapgenius","available_roles":["moderator","mega_boss","in_house_staff","verified_artist","meme_artist","engineer","editor","educator","staff","whitehat","tech_liaison","mediator"],"zeroclipboard_swf_path":"https://assets.genius.com/flash/ZeroClipboard.swf?1478704484","canonical_domain":"genius.com","enable_angular_debug":false,"airbrake_project_id":"7530","airbrake_key":"dcd059598ee876ad6f624f97647f0a8d","airbrake_development_mode":false,"fact_track_launch_article_url":"http://genius.com/a/genius-and-spotify-together","bad_words":["4r5e","5h1t","5hit","a55","anal","anus","ar5e","arrse","arse","ass","ass-fucker","asses","assfucker","assfukka","asshole","assholes","asswhole","a_s_s","b!tch","b00bs","b17ch","b1tch","ballbag","balls","ballsack","bastard","beastial","beastiality","bellend","bestial","bestiality","bi+ch","biatch","bitch","bitcher","bitchers","bitches","bitchin","bitching","bloody","blow job","blowjob","blowjobs","boiolas","bollock","bollok","boner","boob","boobs","booobs","boooobs","booooobs","booooooobs","breasts","buceta","bugger","bum","bunny fucker","butt","butthole","buttmuch","buttplug","c0ck","c0cksucker","carpet muncher","cawk","chink","cipa","cl1t","clit","clitoris","clits","cnut","cock","cock-sucker","cockface","cockhead","cockmunch","cockmuncher","cocks","cocksuck","cocksucked","cocksucker","cocksucking","cocksucks","cocksuka","cocksukka","cok","cokmuncher","coksucka","coon","cox","crap","cum","cummer","cumming","cums","cumshot","cunilingus","cunillingus","cunnilingus","cunt","cuntlick","cuntlicker","cuntlicking","cunts","cyalis","cyberfuc","cyberfuck","cyberfucked","cyberfucker","cyberfuckers","cyberfucking","d1ck","damn","dick","dickhead","dildo","dildos","dink","dinks","dirsa","dlck","dog-fucker","doggin","dogging","donkeyribber","doosh","duche","dyke","ejaculate","ejaculated","ejaculates","ejaculating","ejaculatings","ejaculation","ejakulate","f u c k","f u c k e r","f4nny","fag","fagging","faggitt","faggot","faggs","fagot","fagots","fags","fanny","fannyflaps","fannyfucker","fanyy","fatass","fcuk","fcuker","fcuking","feck","fecker","felching","fellate","fellatio","fingerfuck","fingerfucked","fingerfucker","fingerfuckers","fingerfucking","fingerfucks","fistfuck","fistfucked","fistfucker","fistfuckers","fistfucking","fistfuckings","fistfucks","flange","fook","fooker","fuck","fucka","fucked","fucker","fuckers","fuckhead","fuckheads","fuckin","fucking","fuckings","fuckingshitmotherfucker","fuckme","fucks","fuckwhit","fuckwit","fudge packer","fudgepacker","fuk","fuker","fukker","fukkin","fuks","fukwhit","fukwit","fux","fux0r","f_u_c_k","gangbang","gangbanged","gangbangs","gaylord","gaysex","goatse","god-dam","god-damned","goddamn","goddamned","hardcoresex","hell","heshe","hoar","hoare","hoer","homo","hore","horniest","horny","hotsex","jack-off","jackoff","jap","jerk-off","jism","jiz","jizm","jizz","kawk","knob","knobead","knobed","knobend","knobhead","knobjocky","knobjokey","kock","kondum","kondums","kum","kummer","kumming","kums","kunilingus","l3i+ch","l3itch","labia","lmfao","lust","lusting","m0f0","m0fo","m45terbate","ma5terb8","ma5terbate","masochist","master-bate","masterb8","masterbat*","masterbat3","masterbate","masterbation","masterbations","masturbate","mo-fo","mof0","mofo","mothafuck","mothafucka","mothafuckas","mothafuckaz","mothafucked","mothafucker","mothafuckers","mothafuckin","mothafucking","mothafuckings","mothafucks","mother fucker","motherfuck","motherfucked","motherfucker","motherfuckers","motherfuckin","motherfucking","motherfuckings","motherfuckka","motherfucks","muff","mutha","muthafecker","muthafuckker","muther","mutherfucker","n1gga","n1gger","nazi","nigg3r","nigg4h","nigga","niggah","niggas","niggaz","nigger","niggers","nob","nob jokey","nobhead","nobjocky","nobjokey","numbnuts","nutsack","orgasim","orgasims","orgasm","orgasms","p0rn","pawn","pecker","penis","penisfucker","phonesex","phuck","phuk","phuked","phuking","phukked","phukking","phuks","phuq","pigfucker","pimpis","piss","pissed","pisser","pissers","pisses","pissflaps","pissin","pissing","pissoff","poop","porn","porno","pornography","pornos","prick","pricks","pron","pube","pusse","pussi","pussies","pussy","pussys","rectum","retard","rimjaw","rimming","s hit","s.o.b.","sadist","schlong","screwing","scroat","scrote","scrotum","semen","sex","sh!+","sh!t","sh1t","shag","shagger","shaggin","shagging","shemale","shi+","shit","shitdick","shite","shited","shitey","shitfuck","shitfull","shithead","shiting","shitings","shits","shitted","shitter","shitters","shitting","shittings","shitty","skank","slut","sluts","smegma","smut","snatch","son-of-a-bitch","spac","spunk","s_h_i_t","t1tt1e5","t1tties","teets","teez","testical","testicle","tit","titfuck","tits","titt","tittie5","tittiefucker","titties","tittyfuck","tittywank","titwank","tosser","turd","tw4t","twat","twathead","twatty","twunt","twunter","v14gra","v1gra","vagina","viagra","vulva","w00se","wang","wank","wanker","wanky","whoar","whore","willies","willy","xrated","xxx"],"user_authority_roles":["moderator","editor","mediator"],"user_verification_roles":["community_artist","verified_artist","meme_artist"],"user_vote_types_for_delete":["votes","upvotes","downvotes"],"brightcove_account_id":"4863540648001","mixpanel_delayed_events_timeout":"86400","brightcove_p_relevant_web_player_id":"B18DMWtt","brightcove_hyper_relevant_web_player_id":"SJnP34Jh","brightcove_tag_relevant_web_player_id":"HJwZpTzT","brightcove_modal_web_player_id":"S1LI5bh0","brightcove_amp_p_relevant_web_player_id":"Bkw8GqGkg","brightcove_hot_swap_web_player_id":"SkVaza9A","brightcove_article_web_player_id":"S1ZcmcOC1x"};
  var SESSION_CONFIG = {"current_user":null,"chat_enabled":null,"dfp_enabled":true};
  var AD_CONFIG = {"dfp":{"desktop_home_leaderboard":{"sizes":[[970,250],[728,90]],"kv":{"is_atf":true}},"mobile_home_adhesion":{"sizes":[[320,50]],"kv":{"is_atf":true}},"desktop_home_medium1":{"sizes":[[300,600]],"kv":{"is_atf":false}},"desktop_song_leaderboard":{"sizes":[[970,250],[728,90]],"kv":{"is_atf":true}},"desktop_article_leaderboard":{"sizes":[[970,250],[728,90]],"kv":{"is_atf":true}},"desktop_song_medium1":{"sizes":[[300,600],[300,250]],"kv":{"is_atf":false}},"desktop_song_inread":{"sizes":[[1,1]],"kv":{"is_atf":false}},"desktop_song_lyrics_footer":{"sizes":[[1,1],[300,250],[300,600]],"kv":{"is_atf":false}},"mobile_song_adhesion":{"sizes":[[320,50]],"kv":{"is_atf":true}},"mobile_song_medium1":{"sizes":[[300,250]],"kv":{"is_atf":false}},"mobile_song_footer":{"sizes":[[320,50],[300,250]],"kv":{"is_atf":false}},"amp_song_medium1":{"size":[300,250],"kv":{"is_atf":false}},"amp_song_sticky":{"size":[320,50],"kv":{"is_atf":false}},"amp_song_medium_footer":{"size":[300,250],"kv":{"is_atf":false}},"amp_song_below_player":{"size":[300,250],"kv":{"is_atf":false}},"amp_song_below_song_bio":{"size":[300,250],"kv":{"is_atf":false}},"mobile_article_adhesion":{"sizes":[[320,50]],"kv":{"is_atf":true}},"mobile_article_medium1":{"sizes":[[300,250]],"kv":{"is_atf":false}},"app_song_inread":{"sizes":"MEDIUM_RECTANGLE,BANNER"},"desktop_home_skin":{"sizes":[[1,1]],"kv":{"is_atf":true}},"desktop_song_skin":{"sizes":[[1,1]],"kv":{"is_atf":true}},"desktop_song_annotation":{"sizes":[[300,250],[357,95]],"kv":{"is_atf":false}},"mobile_song_annotation":{"sizes":[[300,250]],"kv":{"is_atf":false}}},"dfp_network_id":"342026871","prebid_placements":{"desktop_728x90":[{"bidder":"aol","params":{"placement":"4166613","network":"10604.1"}},{"bidder":"appnexus","params":{"placementId":"9345913"}},{"bidder":"rubicon","params":{"accountId":"15874","siteId":"107816","zoneId":"513532"}}],"desktop_300x600":[{"bidder":"aol","params":{"placement":"4166614","network":"10604.1"}},{"bidder":"appnexus","params":{"placementId":"9345919"}},{"bidder":"rubicon","params":{"accountId":"15874","siteId":"107816","zoneId":"513532"}}],"desktop_160x600":[{"bidder":"aol","params":{"placement":"4166615","network":"10604.1"}},{"bidder":"rubicon","params":{"accountId":"15874","siteId":"107816","zoneId":"513532"}}],"desktop_300x250":[{"bidder":"aol","params":{"placement":"4166616","network":"10604.1"}},{"bidder":"appnexus","params":{"placementId":"9319415"}},{"bidder":"rubicon","params":{"accountId":"15874","siteId":"107816","zoneId":"513532"}}],"mobile_300x250":[{"bidder":"aol","params":{"placement":"4166676","network":"10604.1"}},{"bidder":"appnexus","params":{"placementId":"9345910"}},{"bidder":"rubicon","params":{"accountId":"15874","siteId":"107816","zoneId":"513532"}}]}}
  var TOP_LEVEL_BLOCK_CONTAINERS = ["address","article","aside","blockquote","div","dl","fieldset","footer","form","h1","h2","h3","h4","h5","h6","header","menu","nav","ol","p","pre","section","table","ul"];
  var TOP_LEVEL_STANDALONE_BLOCKS = ["img","hr"];

    window._taboola = window._taboola || [];
    _taboola.push({article:'auto'});
    !function (e, f, u, i) {
      if (!document.getElementById(i)){
        e.async = 1;
        e.src = u;
        e.id = i;
        f.parentNode.insertBefore(e, f);
      }
    }(document.createElement('script'),
    document.getElementsByTagName('script')[0],
    '//cdn.taboola.com/libtrc/genius/loader.js',
    'tb_loader_script');
  

  var _qevents = _qevents || [];
  (function() {
    var elem = document.createElement('script');
    elem.src = (document.location.protocol == 'https:' ? 'https://secure' : 'http://edge') + '.quantserve.com/quant.js';
    elem.async = true;
    elem.type = 'text/javascript';
    var scpt = document.getElementsByTagName('script')[0];
    scpt.parentNode.insertBefore(elem, scpt);
  })();

  var _gaq = _gaq || [];
  

    _gaq.push(['_setAccount', 'UA-10346621-1']);

    var VISITOR_LEVEL = 1
    var SESSION_LEVEL = 2
    var PAGE_LEVEL = 3

    var logged_in = !!window.CURRENT_USER
    _gaq.push(['_setCustomVar', 1, 'Logged in', String(logged_in), SESSION_LEVEL])
    _gaq.push(['_setCustomVar', 2, 'Controller action', 'songs#show', PAGE_LEVEL])

    if (window.TRACKING_DATA) {
      if ("Primary Tag" in TRACKING_DATA) {
        _gaq.push(['_setCustomVar', 3, "Primary tag", TRACKING_DATA["Primary Tag"], PAGE_LEVEL])
      }

      if ("Music?" in TRACKING_DATA) {
        _gaq.push(['_setCustomVar', 4, "Music", String(TRACKING_DATA["Music?"]), PAGE_LEVEL])
      }
    }

    _gaq.push(['_trackPageview']); // this was causing duplicate pageviews (untill i killed jquery-address)

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

    (function(g, e, n, i, u, s) {
      g['GoogleAnalyticsObject'] = 'ga';
      g.ga = g.ga || function() { (g.ga.q = g.ga.q || []).push(arguments) };
      g.ga.l = Date.now();
      u = e.createElement(n);
      s = e.getElementsByTagName(n)[0];
      u.async = true;
      u.src = i;
      s.parentNode.insertBefore(u, s);
    })(window, document, 'script', 'https://www.google-analytics.com/analytics.js');

    ga('create', "UA-10346621-14", 'auto');
    ga('set', 'dimension1', String(logged_in));
    ga('set', 'dimension2', "songs#show");
    ga('set', 'dimension3', TRACKING_DATA['Primary Tag']);
    ga('set', 'dimension3', String(TRACKING_DATA['Music?']));
    ga('send', 'pageview');
  

  var 
adUnits.push({"code":"div-gpt-ad-Iy2WXzH_mzcKREKyIZh8Mw","sizes":[[300,250]],"bids":[{"bidder":"aol","params":{"placement":"4166616","network":"10604.1"}},{"bidder":"appnexus","params":{"placementId":"9319415"}},{"bidder":"rubicon","params":{"accountId":"15874","siteId":"107816","zoneId":"513532"}}]});
adUnits.push({"code":"div-gpt-ad-Iy2WXzH_mzcKREKyIZh8Mw","sizes":[[300,600]],"bids":[{"bidder":"aol","params":{"placement":"4166614","network":"10604.1"}},{"bidder":"appnexus","params":{"placementId":"9345919"}},{"bidder":"rubicon","params":{"accountId":"15874","siteId":"107816","zoneId":"513532"}}]});
adUnits.push({"code":"div-gpt-ad-4t797_MP6H-EH_99eaQsnQ","sizes":[[300,600]],"bids":[{"bidder":"aol","params":{"placement":"4166614","network":"10604.1"}},{"bidder":"appnexus","params":{"placementId":"9345919"}},{"bidder":"rubicon","params":{"accountId":"15874","siteId":"107816","zoneId":"513532"}}]});
adUnits.push({"code":"div-gpt-ad-4t797_MP6H-EH_99eaQsnQ","sizes":[[300,250]],"bids":[{"bidder":"aol","params":{"placement":"4166616","network":"10604.1"}},{"bidder":"appnexus","params":{"placementId":"9319415"}},{"bidder":"rubicon","params":{"accountId":"15874","siteId":"107816","zoneId":"513532"}}]});

    pbjs.que = pbjs.que || [];

    

    pbjs.que.push(function() {
      pbjs.addAdUnits(adUnits);
      pbjs.requestBids({
        bidsBackHandler: sendAdserverRequest
      });
    });

    function sendAdserverRequest() {
      if (pbjs.adserverRequestSent) return;
      pbjs.adserverRequestSent = true;
      
      });
    }

    setTimeout(function() {
      sendAdserverRequest();
    }, PREBID_TIMEOUT);
  })(
          return {refresh: function() { 
  });

  

    
  });

    {{:: 'cloud_flare_always_on_short_message' | i18n }}
    Check @genius for updates. We'll have things fixed soon.
  

GENIUS

Rap

Pop

Rock

R&B;

Country

France

Deutschland

Polska

Lit

News

Screen

Sports

        {"@context":"http://schema.org","@type":"MusicRecording","byArtist":{"@context":"http://schema.org","@type":"MusicGroup","name":"Cachorro Grande","url":"http://genius.com/artists/Cachorro-grande","description":"Get all the lyrics to songs by Cachorro Grande and join the Genius community of music scholars to learn the meaning behind the lyrics.","image":"https://images.genius.com/4f78ff6671d43f28ce787f0c0b06dfce.600x399x1.jpg"},"image":"https://images.genius.com/d1c0677d1650e6c12d112a9a931867cf.1000x1000x1.jpg","inAlbum":[{"@context":"http://schema.org","@type":"MusicAlbum","byArtist":{"@context":"http://schema.org","@type":"MusicGroup","name":"Cachorro Grande","url":"http://genius.com/artists/Cachorro-grande","description":"Get all the lyrics to songs by Cachorro Grande and join the Genius community of music scholars to learn the meaning behind the lyrics.","image":"https://images.genius.com/4f78ff6671d43f28ce787f0c0b06dfce.600x399x1.jpg"},"image":"https://images.genius.com/d1c0677d1650e6c12d112a9a931867cf.1000x1000x1.jpg","name":"Electromod","url":"http://genius.com/albums/Cachorro-grande/Electromod","datePublished":"2016-08-03","numTracks":10}],"name":"Electromod","url":"http://genius.com/Cachorro-grande-electromod-lyrics","datePublished":"2016-07-29"}
      

Electromod

Cachorro Grande

Produced By

Edu K.

Album
Electromod

Electromod"

**Comment by fr31** [comment]
I think this is fixed.
