### ISSUE TITLE
'Synced Lyrics' option only takes effect on song change

### ISSUE THREAD

**Issue by Azaxiel** [fr31/spotifylyrics#37]
If the Synced Lyrics option is on when lyrics are loaded for the currently playing song, and the user turns them off, they will remain on until the song changes. The same goes for if the option is disabled when lyrics are loaded. 

Also, completely unrelated, but I thought something like this might be useful to this project: https://github.com/cgbystrom/spotify-local-http-api

**Comment by beppe9000** [comment]
A refresh button that forces a reload of the lyrics could be a solution

**Comment by fr31** [comment]
This should be fixed.
