### ISSUE TITLE
musixmatch failing

### ISSUE THREAD

**Issue by beppe9000** [fr31/spotifylyrics#44]
I'm getting `Error: Could not find lyrics.` on [luca turilli's rhapsody - yggdrasil](https://open.spotify.com/track/202xjdToyzM8fZP22NargS) that indeed is available [on musixmatch](https://www.musixmatch.com/lyrics/Luca-Turilli-s-Rhapsody-2/Yggdrasil). I see you have musixmatch in the backend code but i checked with a sniffer and no request is ever made to it. Edit: there is a http connection attempt (tunnel) but no https request is ever sent. Is proxying toggleable, if you are doing it (i saw some proxy class or property in the code)?

**Comment by Arecsu** [comment]
Solved minutes ago with #47!
