### ISSUE TITLE
Cannot install downloaded executable file

### ISSUE THREAD

**Issue by shutrmovick** [fr31/spotifylyrics#51]
When I try to open the .exe file, I get a system error which says : 
![error1](https://cloud.githubusercontent.com/assets/25284768/22185058/4466aa14-e104-11e6-9445-1640c5d07e54.png)

and after closing the system error window, I get a fatal error message saying :
![error1](https://cloud.githubusercontent.com/assets/25284768/22185061/67c755da-e104-11e6-9e87-cebdfc4414e7.png)

**Comment by fr31** [comment]
From the readme:

> If you get an error about api-ms-win-crt-runtime-l1-1-0.dll missing, you need this:

https://www.microsoft.com/en-us/download/details.aspx?id=48145
