### ISSUE TITLE
Binaries are being blocked by Avast DeepScreen

### ISSUE THREAD

**Issue by uszasty** [fr31/spotifylyrics#6]
I'm running Windows 10 up to date, Avast Antivirus free, also up to date. When I'm trying to ru SpotifyLyrics with DeepScreen on, explorer window freeze.

**Comment by fr31** [comment]
I've googled it a bit and this issue seems to affect all binaries made with pyinstaller since at least 2014. If avast allows whitelisting I would recommend that, but other than that, I'm not sure what to do about this issue.
