### ISSUE TITLE
'Ui_Form' object has no attribute 'lyricsTextAlign'

### ISSUE THREAD

**Issue by sdz2** [fr31/spotifylyrics#60]
Upon playing a song in Spotify, I get the following error.
```
Traceback (most recent call last):
  File "./SpotifyLyrics.pyw", line 374, in refresh_lyrics
    self.set_lyrics_with_alignment(_translate("Form", lyrics))
  File "./SpotifyLyrics.pyw", line 259, in set_lyrics_with_alignment
    self.textBrowser.setAlignment(self.lyricsTextAlign)
AttributeError: 'Ui_Form' object has no attribute 'lyricsTextAlign'
Aborted (core dumped)
```
System info:
```
  Gentoo Linux 4.12.5-gentoo x86_64
  python 3.4.5
  = beautifulsoup4 4.5.1
  * PyQt5 5.7.1  > 5.7
  * requests 2.12.5 > 2.11.1
  * sip 4.19.1 > 4.18.1
  = xmltodict 0.10.2

= Exact version installed
* Newer version installed

$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
```

Thoughts?

**Comment by sdz2** [comment]
Temporary workaround:  I added ```self.lyricsTextAlign = QtCore.Qt.AlignLeft``` to ```Ui_Form.setupUi(self, Form)```.

**Comment by Arecsu** [comment]
Good workaround. I solved it by adding a try and except. In the end, it produces the same result. Maybe we could search a more "elegant" solution.

```
def set_lyrics_with_alignment(self, lyrics):
    self.textBrowser.clear()
    for line in lyrics.splitlines():
        self.textBrowser.append(line)
        try:
            self.textBrowser.setAlignment(self.lyricsTextAlign)
        except AttributeError:
            pass
```

#https://github.com/Arecsu/spotifylyrics/commit/4797a444dbd307809c0e1467956b967a5195254f

**Comment by fr31** [comment]
Thanks for fixing this.

**Comment by HF0** [comment]
An exception is raised because the lyricsTextAlign field is not initialized if the property is not found in the .ini file. The fix by @sdz2 looks good and elegant to me. @fr31: Do you want me to create a pull request with the solution by sdz2 or should we leave it as it is now?

**Comment by fr31** [comment]
I moved it to set_style.
