### ISSUE TITLE
Update the build

### ISSUE THREAD

**Issue by Arecsu** [fr31/spotifylyrics#62]
I always end up having problems with the compilations and libraries, I don't know why, and I finish with many headaches. So if you could update this with the last commits, I would appreciate it so much. 

Thanks!

**Comment by fr31** [comment]
Build has been updated. You're right about it being a headache, had to update to the dev build of pyinstaller to get it to work with python 3.6 and my anti-virus kept deleting the 32 bit version. :weary:
