### ISSUE TITLE
Error: Could not find lyrics.

### ISSUE THREAD

**Issue by monmol** [fr31/spotifylyrics#63]

**Comment by monmol** [comment]
Couldn't find lyrics for any song...

**Comment by fr31** [comment]
Gonna need more detail than that.

Specific song names?
OS?
Source or exe?
Version?
64 bit or 32 bit?
Any error message?

Are you sure it's not your firewall/anti-virus/anything else that could cause an issue with your network connection?

Can't really provide anything other than "it's working fine for me" without more info. :)
