### ISSUE TITLE
Add Ctrl+Scroll to Adjust Font Size (or Zoom)

### ISSUE THREAD

**Issue by sdz2** [fr31/spotifylyrics#66]
Suggestion:
Add the shortcut <kbd>Ctrl</kbd>+<kbd>Scroll Wheel</kbd> to adjust font size (or zoom).

Reason:
When a new song plays, I often adjust the font size for the lyrics to fit better.  I frequently try to adjust zoom with Ctrl+Scroll, as it used in many other applications.  Sadly, it doesn't work here.

Using the tiny font-size control works but is far more tedious.

**Comment by xDebuggerx** [comment]
Good suggestion!

**Comment by sdz2** [comment]
@xDebuggerx - Do you happen to be less busy a month later?

**Comment by HF0** [comment]
Hi sdz2,
I have implemented the ctrl+scroll feature.  I have created a pull request.
You can use the version from my repository in the meantime.

**Comment by sdz2** [comment]
Your feature works great!  Thank you!

This highlights another issue #71 where the currently playing line (indicated in bold) is lost when changing font size.

**Comment by fr31** [comment]
Sorry it took so long, but I merged the pull request.
