### ISSUE TITLE
Lyrics provider

### ISSUE THREAD

**Issue by KodaPOwER** [fr31/spotifylyrics#7]
Hello, congratz for this little piece of great software.

I think it can be great if you show up the lyric provider next to the song title, and make it clickable to open up the original lyric page. Can you make this?

Sorry, I do not know python otherwise I would have made a pull request.

**Comment by fr31** [comment]
Everything I tried next to the song title looked really ugly and out of place so I just made the song title clickable in the latest release. Hope that's good enough.

**Comment by KodaPOwER** [comment]
Yeah, that's good enough, thanks!
