### ISSUE TITLE
Lyrics pulled from Genuis return page source rather than lyrics.

### ISSUE THREAD

**Issue by DashAlpha** [fr31/spotifylyrics#73]
Pretty much returns a bunch of page data and no lyrics.  

Image Below:
![image](https://user-images.githubusercontent.com/35820768/35417447-55446adc-0292-11e8-80a0-879f066d6b29.png)

**Comment by fr31** [comment]
This should be fixed in 1.18.

**Comment by DashAlpha** [comment]
Yep, working great.  Thanks!
