### ISSUE TITLE
[Suggestion] Dark theme

### ISSUE THREAD

**Issue by bathrobehero** [fr31/spotifylyrics#74]
This is NOT an issue, I was just no sure where to contact the devs.

So I think it would be awesome if we could have a dark theme, similar to Spotify (white text on dark grey - RGB 24;24;24) to match its theme.

Also, what donation methods exists?

**Comment by fr31** [comment]
It's not perfect but I made this awhile ago based off the spotify theme.

`WindowOpacity = 1.0
BackgroundColor = #282828
LyricsBackgroundColor = #181818
LyricsTextColor = #ffffff
SongNameColor = #9c9c9c
FontBoxBackgroundColor = #181818
FontBoxTextColor = #9c9c9c`

Here's another dark one I made based off a theme for Steam I use.

`WindowOpacity = 1.0
BackgroundColor = #1a1a1a
LyricsBackgroundColor = #0e0e0e
LyricsTextColor = #ffffff
SongNameColor = #868889
FontBoxBackgroundColor = #0e0e0e
FontBoxTextColor = #868889`

Just copy/paste either of those in theme.ini.

Don't accept donations but you could donate to a good charity instead. :)

**Comment by bathrobehero** [comment]
This is perfect, thanks!
