### ISSUE TITLE
Latest version (1.16) being detected by windows defender as a threat

### ISSUE THREAD

**Issue by hvitsaerk** [fr31/spotifylyrics#78]
Latest version (1.16) being detected by windows defender as a threat when trying to launch. Previous versions didn't have this issue.

**Comment by fr31** [comment]
I just scanned and launched the x86 and x86_64 version with Windows Defender (real-time protection on) on Windows 10 and I am not getting this issue. 

Is anyone else having this issue?

**Comment by Arecsu** [comment]
Nope. I use windows defender too. Maybe is because the code that explore
the process to catch the one that handles the Spotify window? Nothing to do
if this is the case, report it to Avast as false positive.

**Comment by fr31** [comment]
Since this seems to be an isolated false positive I'm gonna close this issue. Make sure you downloaded it from here and maybe try the new version (1.17). If it persists the only thing I can really recommend is to add it to your whitelist.
