### ISSUE TITLE
Error: Could not find lyrics. 

### ISSUE THREAD

**Issue by swiftaes** [fr31/spotifylyrics#79]
I get Error: Could not find lyrics when I had used the program earlier to find lyrics to the same song and it worked fine. Please reply with what other info you need if any.

**Comment by MiniDigger** [comment]
Which version do you run? I believe this was just fixed with the latest release.

**Comment by francescofresca** [comment]
Hi
I downloaded the latest version 1.16 
but I have the same problem reported. 
For example I have searched for the lyrics of the song in the attached screenshot 

![2018-03-06 12_30_55-pretty solero vicoli lyrics _ genius lyrics](https://user-images.githubusercontent.com/6067543/37030389-0b4d5a84-213b-11e8-94e5-11ee8a512c5c.png) 

but despite being present on the web the plugin says that he has not found it. 

I have seen that a call is made to the site genius. com with the http protocol.
and the site returns an error 404 or if it finds an error 301 by redirecting the site with protocol in https

Can you verify? 
Thanks again for your work

**Comment by Arecsu** [comment]
With the same song, it works for me, but just Musixmatch. Genius seems broken again. They must have changed the structure of their page

![image](https://user-images.githubusercontent.com/12679098/37047812-d60544e4-214a-11e8-9c98-39a9021211e0.png)

**Comment by swiftaes** [comment]
1.16 is the version I was using when this happened.

**Comment by fr31** [comment]
I think I fixed this. Can someone try 1.18 to confirm?

**Comment by swiftaes** [comment]
Haven't got it with 1.8 :)
