### ISSUE TITLE
SpotifyLyrics crash on Windows 7 64bit

### ISSUE THREAD

**Issue by delbv9** [fr31/spotifylyrics#8]
Here's the problem details:
> Problem signature:
>   Problem Event Name:	APPCRASH
>   Application Name:	SpotifyLyrics-x86_64.exe
>   Application Version:	0.0.0.0
>   Application Timestamp:	30013205
>   Fault Module Name:	Qt5Gui.dll
>   Fault Module Version:	5.6.0.0
>   Fault Module Timestamp:	56d82d8f
>   Exception Code:	c0000005
>   Exception Offset:	000000000001f057
>   OS Version:	6.1.7601.2.1.0.256.1
>   Locale ID:	1033
>   Additional Information 1:	c33f
>   Additional Information 2:	c33ff492a47b18df3d84bf0019a1fe6b
>   Additional Information 3:	ac90
>   Additional Information 4:	ac905523b634a411fb4e2357df26c82e
> 
> Read our privacy statement online:
>   http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409
> 
> If the online privacy statement is not available, please read our privacy statement offline:
>   C:\Windows\system32\en-US\erofflps.txt

Thank you.

**Comment by fr31** [comment]
Does this happen when it's first launched or after it's been running? At a specific song maybe?

**Comment by delbv9** [comment]
@fr31 No. It doesn't happen regularly. It just happened out of the blue. I will check it in again with what song made it crash.

**Comment by fr31** [comment]
Any updates on this?
