### ISSUE TITLE
Wrong lyrics

### ISSUE THREAD

**Issue by Claymorne** [fr31/spotifylyrics#85]
I know lyrics and the internet don't always go hand in hand, so I was wondering how I could help contribute to the lyrics library. 

Example of wrong lyrics:
Green Day - American Idiot

> Don't want a nation that under the new media

Media = Mania

> Well maybe I'm the fuckhead America

Fuckhead = Faggot

**Comment by fr31** [comment]
The program fetches lyrics from various third party websites so if you wanted to contribute to the lyrics library you'd have to go to them.

If you click the song name in spotifylyrics it will open the page where it got the lyrics from. You'll then want to look for an edit/correct lyrics link depending on the the site if it is available.

The short term solution would be to hit the "Change Lyrics" button and hope the next one is correct.
