### ISSUE TITLE
I designed an icon.

### ISSUE THREAD

**Issue by OzgurGorgulu** [fr31/spotifylyrics#9]
I designed an icon for this program.
[https://lh3.googleusercontent.com/-rBYgfBrFzRY/V5IzLG0UrII/AAAAAAAARKU/CHlue5H8BqYc0jjiOWQfyLH-l-0aQLmugCCo/s512/spotify-lyrics.png](url)

**Comment by fr31** [comment]
Thanks! It looks nice. You should fork the repo, rename it to icon.png, replace the current icon, and then submit a pull request so you show up under the "contributors" section. Or I'll just add it my self in the next version. Up to you.

**Comment by fr31** [comment]
Hm. Guess it doesn't list image contributions there. My bad. Still shows you when you click the image though. It'll be the icon in the next release. Thanks.
