### ISSUE TITLE
is anybody else forking this project and maintaining it?

### ISSUE THREAD

**Issue by kamalhm** [fr31/spotifylyrics#93]

**Comment by EmanueleS2** [comment]
I was thinking about it, i've almost finished my own C# application for this purpose and i just found this.

**Comment by kamalhm** [comment]
nice! tell me when it's available 😁

**Comment by kamalhm** [comment]
> I'm doing it, currently

Wow thanks! Anyway you can build it to .exe ?

**Comment by SimonIT** [comment]
That's somehow the problem. I can't pyinstaller get working😅

**Comment by kamalhm** [comment]
Can you make an instruction on how to run it on windows? Also maybe update the requirements.txt so I can try it?

**Comment by SimonIT** [comment]
See [here](https://github.com/SimonIT/spotifylyrics/releases) for releases (and exe's)
